name: desafio_nextar
description: Defafio Nextar.

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http:
  provider:
  get:
  equatable:
  flutter_secure_storage:
  lottie:
  localstorage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito:

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/
